.PHONY: clean All

All:
	@echo "----------Building project:[ GLCube - Debug ]----------"
	@"$(MAKE)" -f  "GLCube.mk"
clean:
	@echo "----------Cleaning project:[ GLCube - Debug ]----------"
	@"$(MAKE)" -f  "GLCube.mk" clean
